name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv eb-env
        . eb-env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install AWS Elastic Beanstalk CLI
      run: |
        . eb-env/bin/activate
        pip install awsebcli

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        . eb-env/bin/activate
        eb init -p python-3.8 my-eb-app --region $AWS_REGION
        if eb status my-eb-env; then
          echo "Environment exists, deploying..."
          eb deploy
        else
          echo "Environment does not exist, creating..."
          eb create my-eb-env
          eb deploy
        fi

    - name: Fetch EB Logs on Failure
      if: failure()
      run: |
        . eb-env/bin/activate
        eb logs --all

